### ISSUE TITLE
[Question] use with DDNS

### ISSUE THREAD

**Issue by SalimiHabib** [natemcmaster/LettuceEncrypt#262] opened 2022-08-15 06:59 UTC
is it possible to use  DNS challenge that handled by DDNS and text record in my  domain registrar service ?

**Comment by natemcmaster** [comment] 2023-01-01 20:25
No, it's not possible unless someone implements #1.

Unless someone else implements, I'm unlikely to add this feature (see project status #189).

Closing as a duplicate of  #1.

**Closed by natemcmaster** 2023-01-01 20:25 UTC
Labels: question
